  name: raspberrypi_onvif_rtspServer
  version: git
  summary: v4l2 RTSP ONVIF 
  description: |
    * raspberrypi_onvif_rtspServer :
    build server stream from v4l2 device and detect it as onvif device

  grade: stable 
  confinement: strict
  base: core22

  parts:
    v4l2onvif:
      plugin: make
      make-parameters: ["-j1"]
      source: .
      source-type: git
      build-packages:
      - g++
      - cmake
      - pkg-config
      - autoconf 
      - automake 
      - libtool
      - gsoap 
      - libgsoap-dev 
      - libssl-dev
      - zlib1g-dev
      stage-packages:
      - libgsoap-dev
      - libssl-dev

  apps:
    server:
      command: onvif-server.exe -H $http_port -P $rtsp_port -i $devices
      daemon: simple
      plugs: [network-bind, camera]

    client:
      command: onvif-client.exe 

